name: witchcraft
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  logger: ^2.6.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  image: "assets/WhitchCraft.png"
  android_12:
    image: "assets/WhitchCraft.png"
    color: "#ffffff"
  



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/iconTitleless.png"
  




  

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icon.png
   - assets/iconW.png
   - assets/titleless.png
   - assets/3.png
   - assets/5.png
   - assets/iconTitleless.png
   - assets/WhitchCraft.png
   - assets/leerTarot.png
   - assets/Button1.jpg
   - assets/Button2.jpg
   - assets/tarot.jpg
   - assets/Symbology.jpg
   - assets/Numerology.jpg
   - assets/moreTools.jpg
   - assets/protections.jpg
   - assets/elements.jpg
   - assets/water.jpg
   - assets/uno.jpg
   - assets/talisman.jpg
   - assets/ojo.jpg
   - assets/pendulo.jpg
   # Tarot Rider - Waite
   #Arcanes
   - assets/Rider_Waite_Tarot/Fool.jpg
   - assets/Rider_Waite_Tarot/Magician.jpg
   - assets/Rider_Waite_Tarot/High_Priestess.jpg
   - assets/Rider_Waite_Tarot/Empress.jpg
   - assets/Rider_Waite_Tarot/Emperor.jpg
   - assets/Rider_Waite_Tarot/Hierophant.jpg
   - assets/Rider_Waite_Tarot/Lovers.jpg
   - assets/Rider_Waite_Tarot/Chariot.jpg
   - assets/Rider_Waite_Tarot/Strength.jpg
   - assets/Rider_Waite_Tarot/Hermit.jpg
   - assets/Rider_Waite_Tarot/Wheel_of_Fortune.jpg
   - assets/Rider_Waite_Tarot/Justice.jpg
   - assets/Rider_Waite_Tarot/Hanged_Man.jpg
   - assets/Rider_Waite_Tarot/Death.jpg
   - assets/Rider_Waite_Tarot/Temperance.jpg
   - assets/Rider_Waite_Tarot/Devil.jpg
   - assets/Rider_Waite_Tarot/Tower.jpg
   - assets/Rider_Waite_Tarot/Star.jpg
   - assets/Rider_Waite_Tarot/Moon.jpg
   - assets/Rider_Waite_Tarot/Sun.jpg
   - assets/Rider_Waite_Tarot/Judgement.jpg
   - assets/Rider_Waite_Tarot/World.jpg
    #Cups
   - assets/Rider_Waite_Tarot/Cups01.jpg
   - assets/Rider_Waite_Tarot/Cups02.jpg
   - assets/Rider_Waite_Tarot/Cups03.jpg
   - assets/Rider_Waite_Tarot/Cups04.jpg
   - assets/Rider_Waite_Tarot/Cups05.jpg
   - assets/Rider_Waite_Tarot/Cups06.jpg
   - assets/Rider_Waite_Tarot/Cups07.jpg
   - assets/Rider_Waite_Tarot/Cups08.jpg
   - assets/Rider_Waite_Tarot/Cups09.jpg
   - assets/Rider_Waite_Tarot/Cups10.jpg
   - assets/Rider_Waite_Tarot/Cups11.jpg
   - assets/Rider_Waite_Tarot/Cups12.jpg
   - assets/Rider_Waite_Tarot/Cups13.jpg
   - assets/Rider_Waite_Tarot/Cups14.jpg
   #Pents
   - assets/Rider_Waite_Tarot/Pents01.jpg
   - assets/Rider_Waite_Tarot/Pents02.jpg
   - assets/Rider_Waite_Tarot/Pents03.jpg
   - assets/Rider_Waite_Tarot/Pents04.jpg
   - assets/Rider_Waite_Tarot/Pents05.jpg
   - assets/Rider_Waite_Tarot/Pents06.jpg
   - assets/Rider_Waite_Tarot/Pents07.jpg
   - assets/Rider_Waite_Tarot/Pents08.jpg
   - assets/Rider_Waite_Tarot/Pents09.jpg
   - assets/Rider_Waite_Tarot/Pents10.jpg
   - assets/Rider_Waite_Tarot/Pents11.jpg
   - assets/Rider_Waite_Tarot/Pents12.jpg
   - assets/Rider_Waite_Tarot/Pents13.jpg
   - assets/Rider_Waite_Tarot/Pents14.jpg
   #Swords
   - assets/Rider_Waite_Tarot/Swords01.jpg
   - assets/Rider_Waite_Tarot/Swords02.jpg
   - assets/Rider_Waite_Tarot/Swords03.jpg
   - assets/Rider_Waite_Tarot/Swords04.jpg
   - assets/Rider_Waite_Tarot/Swords05.jpg
   - assets/Rider_Waite_Tarot/Swords06.jpg
   - assets/Rider_Waite_Tarot/Swords07.jpg
   - assets/Rider_Waite_Tarot/Swords08.jpg
   - assets/Rider_Waite_Tarot/Swords09.jpg
   - assets/Rider_Waite_Tarot/Swords10.jpg
   - assets/Rider_Waite_Tarot/Swords11.jpg
   - assets/Rider_Waite_Tarot/Swords12.jpg
   - assets/Rider_Waite_Tarot/Swords13.jpg
   - assets/Rider_Waite_Tarot/Swords14.jpg
   #Wands
   - assets/Rider_Waite_Tarot/Wands01.jpg
   - assets/Rider_Waite_Tarot/Wands02.jpg
   - assets/Rider_Waite_Tarot/Wands03.jpg
   - assets/Rider_Waite_Tarot/Wands04.jpg
   - assets/Rider_Waite_Tarot/Wands05.jpg
   - assets/Rider_Waite_Tarot/Wands06.jpg
   - assets/Rider_Waite_Tarot/Wands07.jpg
   - assets/Rider_Waite_Tarot/Wands08.jpg
   - assets/Rider_Waite_Tarot/Wands09.jpg
   - assets/Rider_Waite_Tarot/Wands10.jpg
   - assets/Rider_Waite_Tarot/Wands11.jpg
   - assets/Rider_Waite_Tarot/Wands12.jpg
   - assets/Rider_Waite_Tarot/Wands13.jpg
   - assets/Rider_Waite_Tarot/Wands14.jpg
   #back
   - assets/Rider_Waite_Tarot/Back.jpg
  
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IMFell
      fonts:
        - asset: fonts/IMFellEnglish-Italic.ttf
          style: italic
        - asset: fonts/IMFellEnglish-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
